#!/usr/bin/env python3
"""Regenerate the README leaderboard from results.csv.

results.csv is the single source of truth. Adding a model means adding one line
there and re-running this script; the three README views are derived, never
hand-edited.

    python tools/gen_leaderboard.py           # rewrite README.md in place
    python tools/gen_leaderboard.py --check   # exit 1 if README is stale (for CI)
    python tools/gen_leaderboard.py --stdout  # print the block, touch nothing

CSV columns
    family      MIM | JEA | Hybrid | VLM | GEN
    method      MAE, DINOv3, SigLIP2, ...
    arch        ViT-L/16, RN-50, DiT-XL/2, ...
    pretrain    pre-training dataset
    eval        evaluation dataset
    image_size  evaluation resolution in pixels
    lp          linear-probing top-1
    lp_gap      yes if LP used GAP instead of [CLS] (renders the marker)
    ep          efficient-probing top-1
    ep_queries  winning --ep_queries for the EP number (blank if unknown)
    ep_variant  'ep' or 'ep_all' — which one the EP number came from (blank if unknown)
    model       exact --model string
    loader      openclip | timm | radio | simmim | dinov3 | hub | "" (default models_vit)
                or "unsupported:<name>" when this repo has no loader for it yet
    pretrain_tag  --openclip_pretrain value, for openclip rows
    finetune    --finetune value (timm tag or checkpoint path)
    lp_variant  cls | pos — which one produced the LP number
    lp_log      repo-relative path to the LP training log (blank if not published)
    ep_log      repo-relative path to the EP training log (blank if not published)
    notes       free text; non-empty rows are listed under Provenance
    ep_head     peak | final | blank -- whether the released EP head on HF is the
                run's best epoch (reproduces the table number) or its final epoch

A row is REPRODUCIBLE only when model, loader, ep_queries, ep_variant and
lp_variant are all recorded. Anything else is reported as unverified rather
than guessed.
"""
import argparse
import csv
import re
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV = REPO / "results.csv"
README = REPO / "README.md"

START = "<!-- LEADERBOARD:START -->"
END = "<!-- LEADERBOARD:END -->"
AUTOGEN = "<!-- generated by tools/gen_leaderboard.py from results.csv - do not edit by hand -->"

FAMILY_ORDER = ["MIM", "JEA", "Hybrid", "VLM", "GEN"]
SCALE_ORDER = ["Small", "Base", "Large", "Giant", "Other"]
MARK_NO_CLS = "<sup>&Dagger;</sup>"     # encoder has no [CLS] to probe
MARK_ATTN   = "<sup>&sect;</sup>"       # encoder has a pooled output, but its own
                                        # learned attention pooling produced it
MARK_EP_ALL = "<sup>&dagger;</sup>"     # EP read patch tokens + the [CLS], not patches alone


NOTES_BLOCK = [
    '**Notes.**',
    '',
    '- All numbers are top-1 accuracy at the **best epoch**, over a 90-epoch schedule with LARS,',
    '  `--blr 0.1` and effective batch 4096.',
    '- **k-NN** is training-free: features are extracted once, L2-normalised, and val images are',
    '  classified by weighted vote over their neighbours in the train split. We sweep',
    '  *k* &isin; {5…200} and *T* &isin; {0.07, 0.1, 0.2}; the winning pair is in `knn_k`/`knn_T`.',
    '- **LP** reads the `[CLS]` token, or GAP over patch tokens where no usable `[CLS]` exists',
    '  &mdash; marked <sup>&Dagger;</sup> when the encoder has none (Hiera, DiT, AIMv2, I-JEPA) and',
    '  <sup>&sect;</sup> when it has one but produced by its own learned attention pooling (SigLIP,',
    '  SigLIP2, PE-Core). **k-NN reads the same representation as the LP**, so it carries the same marker.',
    '- **EP** reads patch tokens, or patch tokens **plus** the `[CLS]` for encoders whose',
    '  pre-training objective is defined on that token &mdash; marked <sup>&dagger;</sup>.',
    '- Both variant choices follow from **what the encoder was trained to optimise**, never from',
    '  running both and keeping the higher number. See below for the evidence, including the cases',
    '  where the rule costs us.',
    '- **Q**: rows carried over from the paper report the best over a sweep of *Q*; rows we measured',
    '  use **Q = 32 only**, so they are a lower bound. Beating one with a better *Q* is a welcome PR.',
    '- **LP and EP do not always read a feature of the same width.** Each probes the',
    "  representation it is defined on &mdash; LP the encoder's own pooled output, EP the patch",
    '  tokens &mdash; and for 7 rows those differ in size. On the five CLIP-family rows (CLIP',
    '  ViT-L/14, EVA02-CLIP E-14 and E-14-plus, MetaCLIP2 ViT-bigG/14 at both resolutions)',
    '  `--cls_features cls` returns the *projected* embedding, **narrower** than the unprojected',
    '  patch tokens EP pools &mdash; 1280 vs 1664 for MetaCLIP2, 1024 vs 1792 for EVA02-CLIP &mdash;',
    '  so LP is the handicapped arm there. On the two RADIO rows it runs the other way and further:',
    '  `cls_token_per_teacher=True` makes the summary three separate `[CLS]` tokens that LP receives',
    '  concatenated, giving LP a **3&times; wider** feature than EP (3072 vs 1024 for ViT-L/16).',
    '  RADIO ViT-L/16 is one of only two rows where LP beats EP, so that win is not a like-for-like',
    '  comparison and should not be read as one.',
    '- **Image size** is the evaluation resolution and is not constant (256 for SigLIP/SigLIP2/DiT,',
    '  336 for PE-Core, 378 for MetaCLIP2-378), so rows at different resolutions are not exactly',
    '  like-for-like.',
    '- **EP heads are downloadable**: the *EP head* column links each row\'s trained head on',
    '  [HuggingFace](https://huggingface.co/billpsomas/efficient-probing-heads). *peak* means the',
    '  file is the run\'s best epoch and reproduces the EP number exactly; *final* means the',
    '  run\'s last epoch, whose own accuracy is recorded in the file\'s metadata next to the',
    '  table figure. The split exists because the training code initially kept only a rolling',
    '  per-epoch checkpoint, so finished runs left their final epoch behind; best-epoch saving',
    '  was added later, and the 12 early-peaking models -- where final and best differ most --',
    '  were re-run under identical settings to recapture their peaks. Heads contain no backbone',
    '  weights; each config.json names the encoder.',
]


def scale_of(arch):
    """Bucket an architecture string into a size class."""
    if arch.startswith("SO400M"):
        return "Large"          # ~428M visual params, between ViT-L and ViT-g
    m = re.match(r"ViT-(\w+?)/", arch)
    if m:
        return {"S": "Small", "B": "Base", "L": "Large",
                "H": "Giant", "g": "Giant", "G": "Giant", "e": "Giant"}.get(m.group(1), "Other")
    return "Other"


def load_rows():
    with CSV.open(newline="") as fh:
        rows = list(csv.DictReader(fh))
    required = {"family", "method", "arch", "pretrain", "eval", "image_size", "lp", "lp_gap", "ep"}
    # "notes" is optional
    for i, r in enumerate(rows, start=2):
        missing = required - r.keys()
        if missing:
            sys.exit(f"{CSV}:{i}: missing column(s) {sorted(missing)}")
        for num in ("lp", "ep", "image_size"):
            if r[num].strip() in ("-", ""):
                # "-" means not measured yet. Allowed for lp always, and for ep only
                # when the row carries a 'waiting' note explaining what is outstanding,
                # so a placeholder can never be mistaken for a finished result.
                if num == "lp":
                    continue
                if num == "ep" and r.get("waiting", "").strip():
                    continue
                sys.exit(f"{CSV}:{i}: ep is '-' but there is no 'waiting' note saying why")
            try:
                float(r[num])
            except ValueError:
                sys.exit(f"{CSV}:{i}: column '{num}' is not numeric: {r[num]!r}")
        if r["family"] not in FAMILY_ORDER:
            sys.exit(f"{CSV}:{i}: unknown family {r['family']!r}, expected one of {FAMILY_ORDER}")
        if r["eval"].strip() != "IN-1K":
            sys.exit(f"{CSV}:{i}: eval is {r['eval']!r}, but the README states the whole "
                     f"benchmark is ImageNet-1k and the tables omit the column. Re-add an "
                     f"Evaluation column to render() before adding a non-IN-1K row.")
        if r["lp_gap"].strip().lower() not in ("yes", "no"):
            sys.exit(f"{CSV}:{i}: lp_gap must be yes/no, got {r['lp_gap']!r}")
        if r.get("knn", "").strip() not in ("", "-"):
            try:
                float(r["knn"])
            except ValueError:
                sys.exit(f"{CSV}:{i}: knn is not numeric: {r['knn']!r}")
            if not r.get("knn_k", "").strip():
                sys.exit(f"{CSV}:{i}: knn is set but knn_k is not -- record the winning k")
        if r["lp_gap"].strip().lower() == "yes" and \
                r.get("gap_reason", "").strip() not in ("no_cls", "attn_pool"):
            sys.exit(f"{CSV}:{i}: lp_gap=yes needs gap_reason=no_cls or attn_pool "
                     f"(the two get different markers)")
        if r.get("waiting", "").strip() and r.get("verified", "").strip().lower() == "yes":
            sys.exit(f"{CSV}:{i}: row is ticked but also has a 'waiting' note - clear one")
        if r.get("verified", "").strip().lower() not in ("yes", "no", ""):
            sys.exit(f"{CSV}:{i}: verified must be yes/no/blank, got {r['verified']!r}")
        r["_scale"] = scale_of(r["arch"])
    return rows


def fmt(v):
    """One decimal place, so hand-entered and log-derived values read alike."""
    v = str(v).strip()
    if v in ("-", ""):
        return v
    return f"{float(v):.1f}"


def linked(text, path):
    """Make a number its own evidence: the figure links to the log behind it.

    Every reported number carries its own log, which is why there is no separate
    Logs column -- a reader checking a figure clicks the figure. Markers stay
    OUTSIDE the link so the superscript is not part of the clickable text.
    """
    path = (path or "").strip()
    return f"[{text}]({path})" if path else text


def wins(r):
    """Which of LP / EP is the larger number, or None if they tie.

    Compared on the DISPLAYED (one-decimal) values, so the emphasis always agrees
    with what the reader can see -- bolding 84.36 over 84.35 when both render as
    84.4 would look arbitrary. EP does not always win, and the rows where it loses
    are the point of publishing a benchmark rather than a result.
    """
    try:
        lp, ep = float(fmt(r["lp"])), float(fmt(r["ep"]))
    except ValueError:
        return None
    if lp == ep:
        return None
    return "lp" if lp > ep else "ep"


def lp_cell(r, bold=False):
    if r["lp"].strip() in ("-", ""):
        return "&mdash;"
    cell = linked(fmt(r["lp"]), r.get("lp_log"))
    if bold:
        cell = f"**{cell}**"
    if r["lp_gap"].strip().lower() != "yes":
        return cell
    reason = r.get("gap_reason", "").strip()
    return f"{cell}{MARK_ATTN if reason == 'attn_pool' else MARK_NO_CLS}"


def knn_cell(r):
    """Training-free baseline. Blank until that model's sweep lands.

    k-NN reads the same representation as the LP, so it carries the same marker: a
    reader should be able to see at a glance that both columns are GAP for this row,
    and for the same reason.
    """
    v = r.get("knn", "").strip()
    if v in ("", "-"):
        return "&mdash;"
    cell = linked(fmt(v), r.get("knn_log"))
    if r["lp_gap"].strip().lower() != "yes":
        return cell
    reason = r.get("gap_reason", "").strip()
    return f"{cell}{MARK_ATTN if reason == 'attn_pool' else MARK_NO_CLS}"


HF_HEADS = "https://huggingface.co/billpsomas/efficient-probing-heads/blob/main"


def head_cell(r):
    """Link to the released EP head, the link text saying what the file is.

    "peak" = the run's best epoch, so loading it reproduces the EP number in this
    row exactly. "final" = the run's last epoch; its own accuracy is recorded in
    the file's metadata alongside the table figure. An em-dash means no head
    survives for this row.
    """
    status = r.get("ep_head", "").strip()
    if not status:
        return "&mdash;"
    slug = os.path.basename(os.path.dirname(r["ep_log"]))
    return "[%s](%s/%s/ep_head.pth)" % (status, HF_HEADS, slug)


def ep_cell(r, bold=False):
    """Pending EP renders as an em-dash; ep_all rows carry a marker."""
    if r["ep"].strip() in ("-", ""):
        return "&mdash;"
    cell = linked(fmt(r["ep"]), r.get("ep_log"))
    if bold:
        cell = f"**{cell}**"
    mark = MARK_EP_ALL if r.get("ep_variant", "").strip() == "ep_all" else ""
    return f"{cell}{mark}"


def ep_val(r):
    """Sort key: rows whose EP is still pending sort to the bottom."""
    try:
        return float(r["ep"])
    except ValueError:
        return float("-inf")


def ver_cell(r):
    """Tick = audited. Cross = something is outstanding (see the Waiting on list). Blank = not looked at."""
    if r.get("verified", "").strip().lower() == "yes":
        return "\u2705"
    if r.get("waiting", "").strip():
        return "\u274c"
    return ""


def lp_val(r):
    """Sort key: rows without LP sort last within an EP tie."""
    try:
        return float(r["lp"])
    except ValueError:
        return float("-inf")


def render(rows):
    out = [AUTOGEN, "", "Sorted by **EP**. Ties broken by LP.", ""]

    # --- main leaderboard, ranked by EP ---
    ranked = sorted(rows, key=lambda r: (-ep_val(r), -lp_val(r)))
    out += ["| # | Family | Method | Arch. | Pre-training | Image size | k-NN | LP | EP | EP head |",
            "|---:|---|---|---|---|---:|---:|---:|---:|:-:|"]
    for i, r in enumerate(ranked, start=1):
        out.append(f"| {i} | {r['family']} | {r['method']} | {r['arch']} | {r['pretrain']} | "
                   f"{r['image_size']} | {knn_cell(r)} | {lp_cell(r, wins(r) == 'lp')} | "
                   f"{ep_cell(r, wins(r) == 'ep')} | {head_cell(r)} |")
    waiting = [r for r in rows if r.get("waiting", "").strip()]
    out += [""]
    n_all = sum(1 for r in rows if r.get("ep_variant", "").strip() == "ep_all")
    out += ["**Legend.**", "",
            f"<sup>&dagger;</sup> on an EP number marks the {n_all} rows where EP read the "
            "`[CLS]` token **alongside** the patch tokens (`--cls_features ep_all`) rather than "
            "the patch tokens alone. This is not a search for the better score \u2014 it is used "
            "exactly when the encoder's pre-training objective is defined on that token, so "
            "dropping it would discard what the model was trained to produce. See the EP note "
            "below for the evidence, including the control case where it makes no difference.", "",
            "Two markers distinguish *why* a row's LP is global average pooling rather than "
            "the `[CLS]` token \u2014 they are different situations and only one of them is a "
            "judgement call:", "",
            "- <sup>&Dagger;</sup> \u2014 the encoder has **no `[CLS]` token at all**, so GAP is the "
            "only linear probe available (Hiera, DiT, AIMv2, I-JEPA). Nothing was chosen here.",
            "- <sup>&sect;</sup> \u2014 the encoder **does** expose a pooled output, but it is produced "
            "by the encoder's own learned attention pooling (SigLIP, SigLIP2, PE-Core). Probing "
            "that would measure the pretrained pooler rather than the features, so we use GAP "
            "even when it scores lower \u2014 see the LP note below.", "",

            "Paradigms: **MIM** masked image modelling \u00b7 **JEA** joint-embedding architectures "
            "\u00b7 **Hybrid** MIM + JEA \u00b7 **VLM** vision-language models \u00b7 **GEN** "
            "generative models.", ""]
    out += NOTES_BLOCK + [""]
    if waiting:
        out += ["<details open>",
                f"<summary><b>\u274c Waiting on</b> ({len(waiting)})</summary>", ""]
        for r in sorted(waiting, key=lambda r: -ep_val(r)):
            out.append(f"- **{r['method']} {r['arch']}** \u2014 {r['waiting'].strip()}")
        out += ["", "</details>", ""]

    # --- collapsible: grouped by family ---
    out += ["<details>", "<summary><b>Grouped by family</b> (same rows, ordered by paradigm)</summary>", "",
            "| Family | Method | Arch. | Pre-training | Image size | LP | EP |",
            "|---|---|---|---|---:|---:|---:|"]
    for r in sorted(rows, key=lambda r: (FAMILY_ORDER.index(r["family"]), -ep_val(r))):
        out.append(f"| {r['family']} | {r['method']} | {r['arch']} | {r['pretrain']} | "
                   f"{r['image_size']} | {lp_cell(r, wins(r) == 'lp')} | {ep_cell(r, wins(r) == 'ep')} |")
    out += ["", "</details>", ""]

    # --- collapsible: grouped by backbone scale ---
    out += ["<details>", "<summary><b>Grouped by backbone scale</b></summary>", "",
            "| Scale | Family | Method | Arch. | Image size | LP | EP |",
            "|---|---|---|---|---:|---:|---:|"]
    for r in sorted(rows, key=lambda r: (SCALE_ORDER.index(r["_scale"]), -ep_val(r))):
        out.append(f"| {r['_scale']} | {r['family']} | {r['method']} | {r['arch']} | "
                   f"{r['image_size']} | {lp_cell(r, wins(r) == 'lp')} | {ep_cell(r, wins(r) == 'ep')} |")
    out += ["", "</details>"]

    out += commands_block(rows)

    # Most rows share the same provenance -- our own full-length run with no early
    # stopping -- so state that once and list only what departs from it. A wall of
    # identical sentences is not provenance, it is noise.
    BOILER = ("measured by us; full 90 epochs, no early stopping, both arms",
              "measured by us; full 90 epochs, both arms",
              "measured by us")
    def trimmed(r):
        n = r.get("notes", "").strip()
        for b in BOILER:
            if n.lower().startswith(b.lower()):
                n = n[len(b):].lstrip(" .;,")
                break
        return n
    noted = [r for r in rows if trimmed(r)]
    if noted:
        out += ["", "<details>",
                f"<summary><b>Provenance</b> — more detail on {len(noted)} rows</summary>",
                "", "Unless noted here, a row is our own run: 90 epochs, no early stopping, "
                "both arms, at the settings in its command block.", ""]
        for r in sorted(noted, key=lambda r: -ep_val(r)):
            out.append(f"- `{r['method']} {r['arch']}` — {trimmed(r)}")
        out += ["", "</details>"]

    return "\n".join(out)


BASE = ("torchrun --nproc_per_node=8 main_linprobe.py \\\n"
        "    --epochs 90 --optimizer lars --blr 0.1 --batch_size 512 --accum_iter 1 \\\n"
        "    --dataset_name imagenet1k --nb_classes 1000 --data_path /path/to/imagenet \\\n"
        "    --d_out 1 --amp {amp}")


KNN_BASE = ("torchrun --nproc_per_node=8 main_linprobe.py --knn_eval \\\n"
            "    --T_sweep 0.07,0.1,0.2 --amp {amp} \\\n"
            "    --dataset_name imagenet1k --nb_classes 1000 --data_path /path/to/imagenet")


def base_for(r):
    """Most backbones run in bfloat16; a few need float32 (CAPI)."""
    return BASE.format(amp=(r.get("amp", "").strip() or "bfloat16"))


def backbone_flags(r):
    """The --model plus whatever selects its loader. None if not recorded."""
    model = r.get("model", "").strip()
    if not model:
        return None
    loader = r.get("loader", "").strip()
    tag = r.get("pretrain_tag", "").strip()
    ft = r.get("finetune", "").strip()
    parts = [f"--model {model}"]
    if loader == "openclip":
        parts.append(f"--openclip --openclip_pretrain {tag}")
    elif loader == "timm":
        parts.append("--timm")
    elif loader == "radio":
        parts.append("--radio")
    elif loader == "simmim":
        parts.append("--simmim")
    elif loader == "franca":
        # Deliberately NOT --use_rasa_head. Upstream builds RASAHead(n_pos_layers=9)
        # while both published RASA checkpoints carry only 8 pre_pos_layers, so the
        # flag cannot load against valeoai/Franca v1.0.0 -- it raises before training.
        # Which weights to pull comes from extra_flags below.
        pass
    elif loader == "dinov3":
        parts.append("--dinov3_weights /path/to/dinov3_weights.pth")
    elif loader.startswith("unsupported:"):
        return None
    if ft:
        parts.append(f"--finetune {ft}")
    # Flags a row needs that the loader cannot imply: --no_cls_token for I-JEPA,
    # --franca_weights for Franca. Omitting these published a command that does not
    # reproduce the row's own number, so they belong in every emitted command.
    extra = r.get("extra_flags", "").strip()
    if extra:
        parts.append(extra)
    size = r.get("image_size", "224").strip()
    if size and size != "224":
        parts.append(f"--input_size {size}")
    return " ".join(parts)


def reproducible(r):
    return bool(backbone_flags(r) and r.get("ep_queries") and r.get("ep_variant")
                and r.get("lp_variant"))


def commands_block(rows):
    ok = [r for r in rows if reproducible(r)]
    missing = [r for r in rows if not reproducible(r)]
    out = ["", "<details>",
           "<summary><b>Commands</b> — exact settings behind each row</summary>", ""]
    if ok:
        for r in sorted(ok, key=lambda r: -ep_val(r)):
            parts = []
            if r.get("knn", "").strip():
                parts.append(f"k-NN {fmt(r['knn'])}")
            parts += [f"LP {fmt(r['lp'])}", f"EP {fmt(r['ep'])}"]
            head = f"**{r['method']} {r['arch']}** — " + ", ".join(parts)
            block = [head, "", "```bash"]
            # k-NN first: it trains nothing, so it is the cheapest of the three and the
            # natural starting point. It drops the schedule and optimiser entirely and
            # reads the same representation as the LP. --T_sweep extracts features once
            # and sweeps the temperature in memory; the reported number is the best
            # (k, T), recorded per row in knn_k / knn_T.
            if r.get("knn", "").strip():
                block += [f"# k-NN  (best was k={r['knn_k']}, T={r['knn_T']})",
                          f"{KNN_BASE.format(amp=(r.get('amp','').strip() or 'bfloat16'))} \\",
                          f"    {backbone_flags(r)} \\",
                          f"    --cls_features {r['lp_variant']}", ""]
            block += ["# LP", f"{base_for(r)} \\",
                      f"    {backbone_flags(r)} \\",
                      f"    --cls_features {r['lp_variant']}", "",
                      "# EP", f"{base_for(r)} \\",
                      f"    {backbone_flags(r)} \\",
                      f"    --cls_features {r['ep_variant']} --ep_queries {r['ep_queries']}"]
            out += block + ["```", ""]
    if missing:
        out += ["", "**Settings not yet verified.** These rows are inherited from the paper and we",
                "have not re-run them with recorded settings, so the winning *Q*, the `ep`/`ep_all`",
                "choice, or the loader is unknown:", ""]
        for r in sorted(missing, key=lambda r: -ep_val(r)):
            why = []
            if not r.get("model"):
                why.append("config not recorded")
            elif r.get("loader", "").startswith("unsupported:"):
                why.append(f"no `{r['loader'].split(':')[1]}` loader in this repo yet")
            if not r.get("ep_queries"):
                why.append("winning Q unknown")
            out.append(f"- `{r['method']} {r['arch']}` — {'; '.join(why) or 'incomplete config'}")
    out += ["", "</details>"]
    return out


def splice(readme, block):
    if START not in readme or END not in readme:
        sys.exit(f"{README}: missing {START} / {END} markers")
    head, rest = readme.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{block}\n{END}{tail}"



# --------------------------------------------------------------------------
# Log audit: mechanical checks that a row matches the log it cites.
# The head's parameter count is an independent arithmetic witness of the
# settings -- it cannot be fudged, so it catches a mislabelled ep_queries
# that nothing else would.
#   LP head: C * 1000 + 1000
#   EP head: C^2 + Q*C + C*1000 + 1000        (d_out = 1)
# --------------------------------------------------------------------------

def _read_log(path):
    f = REPO / path
    if not f.exists():
        return None
    best = params = None
    epochs = 0
    truncated = False
    for line in f.read_text(errors="replace").splitlines():
        if line.startswith("Max Accuracy:"):
            best = float(line.split(":")[1].strip().rstrip("%"))
        elif line.startswith("Trainable Parameters:"):
            params = int(line.split(":")[1].strip().replace(",", ""))
        elif line[:1].isdigit() and "," in line:
            epochs += 1
        elif "[early-stop]" in line or "[stopped]" in line:
            truncated = True
    return {"best": best, "params": params, "epochs": epochs, "truncated": truncated}


def _ep_width(params, q):
    """Solve C^2 + C*(q+1000) + 1000 - params = 0; integer C means q is consistent."""
    b = q + 1000
    disc = b * b + 4 * (params - 1000)
    if disc < 0:
        return None
    r = int(round(disc ** 0.5))
    if r * r != disc:
        return None
    c2 = -b + r
    if c2 <= 0 or c2 % 2:
        return None
    return c2 // 2


def audit(rows):
    """Returns (hard_errors, soft_notes)."""
    errs, notes = [], []
    for r in rows:
        who = f"{r['method']} {r['arch']}"
        for kind, col, logcol in (("LP", "lp", "lp_log"), ("EP", "ep", "ep_log")):
            path = r.get(logcol, "").strip()
            if not path:
                continue
            info = _read_log(path)
            if info is None:
                errs.append(f"{who}: {logcol} points at {path}, which does not exist")
                continue
            # (a) the cited log must be the run that produced the number
            claimed = r.get(col, "").strip()
            if info["best"] is not None and claimed not in ("", "-"):
                if abs(info["best"] - float(claimed)) > 0.005:
                    errs.append(f"{who}: {kind} is {claimed} but {path} reports "
                                f"{info['best']:.2f} (stale log, or wrong number)")
            # (b) the head size must agree with the recorded settings
            if info["params"]:
                if kind == "LP":
                    if (info["params"] - 1000) % 1000:
                        errs.append(f"{who}: LP head {info['params']:,} is not C*1000+1000")
                else:
                    q = r.get("ep_queries", "").strip()
                    if q.isdigit():
                        if _ep_width(info["params"], int(q)) is None:
                            errs.append(f"{who}: EP head {info['params']:,} is inconsistent "
                                        f"with ep_queries={q} (settings mislabelled?)")
            # (c) truncation is a note, not an error -- some runs stop at the wall
            if info["truncated"] or (info["epochs"] and info["epochs"] < 90):
                notes.append(f"{who} {kind}: {info['epochs']} epochs"
                             + (" (early-stopped)" if info["truncated"] else ""))
    return errs, notes


def _scan_outputs():
    """Longest run per (model-slug, arm) found under outputs/, for the staleness check."""
    import glob
    found = {}
    for f in glob.glob(str(REPO / "outputs" / "imagenet" / "*" / "*" / "training_log.txt")):
        run = os.path.basename(os.path.dirname(f))
        m = re.match(r"linprobe_(.+?)_(cls|pos|ep|ep_all)_q(\d+)_d1(.*)_imagenet1k$", run)
        if not m:
            continue
        name, arm, q, sfx = m.groups()
        try:
            txt = open(f, errors="replace").read()
        except OSError:
            continue
        rows = [l for l in txt.splitlines() if l[:1].isdigit()]
        if not rows:
            continue
        best = max(float(l.split(", ")[4]) for l in rows)
        key = (name, arm)
        if key not in found or len(rows) > found[key][1]:
            found[key] = (best, len(rows), "early-stop" in txt, run)
    return found


def stale_log_notes(rows, outputs):
    """A committed log that is shorter than a run sitting in outputs/ means a re-run
    was never folded in. This is how Hiera ViT-H sat in the table on 30-epoch
    early-stopped numbers while full 90-epoch runs existed alongside them."""
    notes = []
    for r in rows:
        for kind, col, logcol in (("LP", "lp", "lp_log"), ("EP", "ep", "ep_log")):
            path = r.get(logcol, "").strip()
            if not path:
                continue
            info = _read_log(path)
            if info is None or not info["epochs"]:
                continue
            # A log deliberately trimmed at the early-stopping point is not stale: the
            # trailer has to say so and point at the untrimmed run, and then we trust it.
            try:
                body = (REPO / path).read_text(errors="replace")
            except OSError:
                body = ""
            if "untrimmed" in body and "outputs/" in body:
                continue
            slug = os.path.basename(os.path.dirname(path))
            # Only compare like with like: an LP log against cls/pos runs, an EP log
            # against ep/ep_all runs. Without this an LP log gets measured against the
            # EP run of the same model and every row looks stale.
            want = ("cls", "pos") if kind == "LP" else ("ep", "ep_all")
            variant = r["lp_variant"] if kind == "LP" else r["ep_variant"]
            # A longer run only matters if it actually scored BETTER. An early stop
            # that gave up 44 epochs after the peak costs nothing, and flagging it
            # trains the reader to ignore these notes -- so require a real gain.
            reported = r["lp"] if kind == "LP" else r["ep"]
            try:
                reported = float(reported)
            except ValueError:
                reported = float("-inf")
            cand = [(v, n, es, run) for (nm, arm), (v, n, es, run) in outputs.items()
                    if arm in want and (not variant or arm == variant)
                    and n > info["epochs"] + 2 and _slug_matches(slug, nm)
                    and v > reported + 0.005]
            for v, n, es, run in sorted(cand, key=lambda x: -x[1])[:1]:
                notes.append(
                    "%s %s: reported %.2f from a %d-epoch log%s, but outputs/ holds %s with "
                    "%d epochs scoring %.2f -- fold the better run in or say why not"
                    % (r["method"], r["arch"], reported, info["epochs"],
                       " (early-stopped)" if info["truncated"] else "", run, n, v))
    return notes


def _slug_matches(slug, name):
    """logs/<slug>/ vs the outputs run name, both loosely derived from the model."""
    norm = lambda t: t.replace("_", "").replace("-", "").replace("rerun", "") \
                      .replace("noes", "").replace("v25", "").lower()
    a, b = norm(slug), norm(name)
    # require equality after normalisation: substring matching pairs eva02e14plus
    # with eva02e14, which are different checkpoints
    return a == b


_SIZE_RANK = {"S": 0, "B": 1, "L": 2, "H": 3, "g": 4, "G": 4, "e": 4}


def inverted_scaling_notes(rows):
    """Within one method, a larger backbone scoring below a smaller one is usually a
    truncated run rather than a real result -- that is what exposed Hiera ViT-H."""
    notes = []
    by_method = {}
    for r in rows:
        m = re.match(r"ViT-(\w+?)[/-]", r["arch"])
        if not m or m.group(1) not in _SIZE_RANK:
            continue
        try:
            ep = float(r["ep"])
        except ValueError:
            continue
        by_method.setdefault(r["method"], []).append((_SIZE_RANK[m.group(1)], r["arch"], ep))
    for method, items in sorted(by_method.items()):
        items.sort()
        for (r1, a1, e1), (r2, a2, e2) in zip(items, items[1:]):
            if r2 > r1 and e2 < e1:
                notes.append("%s: %s scores %.2f but the smaller %s scores %.2f -- inverted "
                             "scaling, check whether the larger run was truncated"
                             % (method, a2, e2, a1, e1))
    return notes


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if README is out of date")
    ap.add_argument("--stdout", action="store_true", help="print the block instead of writing")
    ap.add_argument("--audit", action="store_true", help="only run the log audit")
    args = ap.parse_args()

    rows = load_rows()

    errs, notes = audit(rows)
    notes += stale_log_notes(rows, _scan_outputs())
    notes += inverted_scaling_notes(rows)
    if errs:
        for e in errs:
            print("AUDIT FAIL: " + e, file=sys.stderr)
    if args.audit or args.check:
        for n in notes:
            print("  note: " + n)
    if args.audit:
        print(f"audit: {len(errs)} error(s), {len(notes)} note(s)")
        sys.exit(1 if errs else 0)
    if errs:
        sys.exit(f"{len(errs)} audit error(s) - fix results.csv or the logs")

    block = render(rows)

    if args.stdout:
        print(block)
        return

    readme = README.read_text()
    updated = splice(readme, block)

    if args.check:
        if updated != readme:
            sys.exit("README leaderboard is stale - run: python tools/gen_leaderboard.py")
        print(f"README leaderboard is up to date ({len(rows)} rows).")
        return

    if updated == readme:
        print(f"README already up to date ({len(rows)} rows).")
    else:
        README.write_text(updated)
        print(f"README leaderboard regenerated from {CSV.name} ({len(rows)} rows).")


if __name__ == "__main__":
    main()
