#!/usr/bin/env python3
"""Regenerate the README leaderboard from results.csv.

results.csv is the single source of truth. Adding a model means adding one line
there and re-running this script; the three README views are derived, never
hand-edited.

    python tools/gen_leaderboard.py           # rewrite README.md in place
    python tools/gen_leaderboard.py --check   # exit 1 if README is stale (for CI)
    python tools/gen_leaderboard.py --stdout  # print the block, touch nothing

CSV columns
    family      MIM | JEA | Hybrid | VLM | GEN
    method      MAE, DINOv3, SigLIP2, ...
    arch        ViT-L/16, RN-50, DiT-XL/2, ...
    pretrain    pre-training dataset
    eval        evaluation dataset
    image_size  evaluation resolution in pixels
    lp          linear-probing top-1
    lp_gap      yes if LP used GAP instead of [CLS] (renders the marker)
    ep          efficient-probing top-1
"""
import argparse
import csv
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV = REPO / "results.csv"
README = REPO / "README.md"

START = "<!-- LEADERBOARD:START -->"
END = "<!-- LEADERBOARD:END -->"
AUTOGEN = "<!-- generated by tools/gen_leaderboard.py from results.csv - do not edit by hand -->"

FAMILY_ORDER = ["MIM", "JEA", "Hybrid", "VLM", "GEN"]
SCALE_ORDER = ["Small", "Base", "Large", "Giant", "Other"]
MARK = "<sup>&Dagger;</sup>"


def scale_of(arch):
    """Bucket an architecture string into a size class."""
    if arch.startswith("SO400M"):
        return "Large"          # ~428M visual params, between ViT-L and ViT-g
    m = re.match(r"ViT-(\w+?)/", arch)
    if m:
        return {"S": "Small", "B": "Base", "L": "Large",
                "H": "Giant", "g": "Giant", "G": "Giant", "e": "Giant"}.get(m.group(1), "Other")
    return "Other"


def load_rows():
    with CSV.open(newline="") as fh:
        rows = list(csv.DictReader(fh))
    required = {"family", "method", "arch", "pretrain", "eval", "image_size", "lp", "lp_gap", "ep"}
    for i, r in enumerate(rows, start=2):
        missing = required - r.keys()
        if missing:
            sys.exit(f"{CSV}:{i}: missing column(s) {sorted(missing)}")
        for num in ("lp", "ep", "image_size"):
            if num == "lp" and r[num].strip() in ("-", ""):
                continue  # LP not measured yet
            try:
                float(r[num])
            except ValueError:
                sys.exit(f"{CSV}:{i}: column '{num}' is not numeric: {r[num]!r}")
        if r["family"] not in FAMILY_ORDER:
            sys.exit(f"{CSV}:{i}: unknown family {r['family']!r}, expected one of {FAMILY_ORDER}")
        if r["lp_gap"].strip().lower() not in ("yes", "no"):
            sys.exit(f"{CSV}:{i}: lp_gap must be yes/no, got {r['lp_gap']!r}")
        r["_scale"] = scale_of(r["arch"])
    return rows


def lp_cell(r):
    if r["lp"].strip() in ("-", ""):
        return "&mdash;"
    return f"{r['lp']}{MARK}" if r["lp_gap"].strip().lower() == "yes" else r["lp"]


def lp_val(r):
    """Sort key: rows without LP sort last within an EP tie."""
    try:
        return float(r["lp"])
    except ValueError:
        return float("-inf")


def render(rows):
    out = [AUTOGEN, "", "Sorted by **EP**. Ties broken by LP.", ""]

    # --- main leaderboard, ranked by EP ---
    ranked = sorted(rows, key=lambda r: (-float(r["ep"]), -lp_val(r)))
    out += ["| # | Family | Method | Arch. | Pre-training | Evaluation | Image size | LP | EP |",
            "|---:|---|---|---|---|---|---:|---:|---:|"]
    for i, r in enumerate(ranked, start=1):
        out.append(f"| {i} | {r['family']} | {r['method']} | {r['arch']} | {r['pretrain']} | "
                   f"{r['eval']} | {r['image_size']} | {lp_cell(r)} | **{r['ep']}** |")
    out.append("")

    # --- collapsible: grouped by family ---
    out += ["<details>", "<summary><b>Grouped by family</b> (same rows, ordered by paradigm)</summary>", "",
            "| Family | Method | Arch. | Pre-training | Image size | LP | EP |",
            "|---|---|---|---|---:|---:|---:|"]
    for r in sorted(rows, key=lambda r: (FAMILY_ORDER.index(r["family"]), -float(r["ep"]))):
        out.append(f"| {r['family']} | {r['method']} | {r['arch']} | {r['pretrain']} | "
                   f"{r['image_size']} | {lp_cell(r)} | **{r['ep']}** |")
    out += ["", "</details>", ""]

    # --- collapsible: grouped by backbone scale ---
    out += ["<details>", "<summary><b>Grouped by backbone scale</b></summary>", "",
            "| Scale | Family | Method | Arch. | Image size | LP | EP |",
            "|---|---|---|---|---:|---:|---:|"]
    for r in sorted(rows, key=lambda r: (SCALE_ORDER.index(r["_scale"]), -float(r["ep"]))):
        out.append(f"| {r['_scale']} | {r['family']} | {r['method']} | {r['arch']} | "
                   f"{r['image_size']} | {lp_cell(r)} | **{r['ep']}** |")
    out += ["", "</details>"]

    return "\n".join(out)


def splice(readme, block):
    if START not in readme or END not in readme:
        sys.exit(f"{README}: missing {START} / {END} markers")
    head, rest = readme.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{block}\n{END}{tail}"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if README is out of date")
    ap.add_argument("--stdout", action="store_true", help="print the block instead of writing")
    args = ap.parse_args()

    rows = load_rows()
    block = render(rows)

    if args.stdout:
        print(block)
        return

    readme = README.read_text()
    updated = splice(readme, block)

    if args.check:
        if updated != readme:
            sys.exit("README leaderboard is stale - run: python tools/gen_leaderboard.py")
        print(f"README leaderboard is up to date ({len(rows)} rows).")
        return

    if updated == readme:
        print(f"README already up to date ({len(rows)} rows).")
    else:
        README.write_text(updated)
        print(f"README leaderboard regenerated from {CSV.name} ({len(rows)} rows).")


if __name__ == "__main__":
    main()
